# -*- coding: utf-8 -*-
"""
/***************************************************************************
 YandexGeocoder
                                 A QGIS plugin
 description=This plugin is used for package geocoding through yandex geocoding API with you API key

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-09
        copyright            : (C) 2020 by Aldres
        email                : aldres98@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load YandexGeocoder class from file YandexGeocoder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .yandex_geocoder import YandexGeocoder
    return YandexGeocoder(iface)
